version: '3.5'

services:
  database:
    container_name: postgres
    build:
      dockerfile: ./database/Dockerfile
    env_file: database.conf
    ports:
      - 5432:5432
    volumes:
      - /var/opt/scraper:/var/lib/postgresql/data
  parser:
    depends_on:
      - database
    container_name: parser
    build:
      dockerfile: ./parser/Dockerfile
    env_file: database.conf
  server:
    depends_on:
      - database
    container_name: flask
    build:
      dockerfile: ./app/Dockerfile
    env_file: database.conf
    ports:
      - 30006:30006

